# ~/.config/starship.toml
# Thème néon futuriste : cyan / magenta sur fond sombre

add_newline = false
format = """
[](#6be7ff)\
$directory\
[](bg:#b86bff fg:#6be7ff)\
$git_branch$git_status\
[](fg:#b86bff)\
\n$character
"""

[directory]
style = "bg:#6be7ff fg:#0b0f14"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#b86bff fg:#ffffff"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:#b86bff fg:#ffffff"
format = "[$all_status$ahead_behind]($style)"

[character]
success_symbol = "[❯](bold #6be7ff)"
error_symbol = "[❯](bold #ff6b8a)"
vicmd_symbol = "[❮](bold #b86bff)"

