foreground         {foreground}
background         {background}
background_opacity {background.alpha_dec}
cursor             {cursor}

transparent_background_colors {red_lt} {green_lt} {yellow_lt} {blue_lt} {magenta_lt} {cyan_lt} {gray_lt}

color0       {color0}
color8       {color8}
color1       {color1}
color9       {color9}
color2       {color2}
color10      {color10}
color3       {color3}
color11      {color11}
color4       {color4}
color12      {color12}
color5       {color5}
color13      {color13}
color6       {color6}
color14      {color14}
color7       {color7}
color15      {color15}

