
set -g window-status-current-format "#[bg={background}, fg={green_light}]#[bg={green_light}, fg={foreground}]#I #W#[bg={background}, fg={green_light}]"

set -g window-status-format "#[bg={background}, fg={cyan_light}]#[bg={cyan_light}, fg={foreground}]#I #W#[bg={background}, fg={cyan_light}]"

set -g status-style bg={background}
set -g status-right ''
set -g status-left ''

set -g status-justify absolute-centre

set -g window-status-separator " "

