
set -g window-status-current-format "#[bg={background}, fg={color2}]#[bg={color2}, fg={foreground}]#I #W#[bg={background}, fg={color2}]"

set -g window-status-format "#I #W"

set -g status-style bg={background}
set -g status-right ''
set -g status-left ''

set -g status-justify absolute-centre

set -g window-status-separator " | "

