
# background #f0f9ff
# background #d2fdd5
# background_opacity 0.45
# foreground #1A1A1A

include ~/.cache/wal/kitty-solarPunk.conf

text_composition_strategy 2.0 25
font_hinting heacy

editor nvim
shell zsh

cursor_trail 1
confirm_os_window_close 0


font_family      JetBrainsMono NF
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
